package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Add go-trpc to an existing project",
	Long: `Add go-trpc to an existing project. Creates gotrpc.json config, a tRPC
client file, and the generated types directory.

Use "gotrpc create" instead to scaffold a new full-stack project from scratch.`,
	RunE:  runInit,
}

func init() {
	initCmd.Flags().Bool("ws", false, "scaffold with WebSocket support (splitLink + wsLink for subscriptions)")
	initCmd.Flags().String("source", "", "Go source directory (default: auto-detect)")
	initCmd.Flags().String("web", "", "web/frontend directory (default: auto-detect)")
}

const generatedGitignore = `*
!.gitignore
`

func sampleHandlerTemplate() string {
	return `package main

import (
	"context"

	gotrpc "github.com/sebasusnik/go-trpc/pkg/router"
	"github.com/sebasusnik/go-trpc/pkg/adapters/nethttp"
)

// Input/output types — these become TypeScript types via gotrpc generate.

type GetUserInput struct {
` + "\tID string `json:\"id\"`" + `
}

type User struct {
` + "\tID    string `json:\"id\"`" + `
` + "\tName  string `json:\"name\"`" + `
` + "\tEmail string `json:\"email\"`" + `
}

func main() {
	r := gotrpc.NewRouter()

	gotrpc.Query(r, "getUser",
		func(ctx context.Context, input GetUserInput) (User, error) {
			return User{ID: input.ID, Name: "Jane", Email: "jane@example.com"}, nil
		},
	)

	r.PrintRoutes("/trpc", ":8080")
	srv := nethttp.NewServer(r, nethttp.Config{Addr: ":8080"})
	srv.Start()
}
`
}

func trpcHTTPTemplate(routerName string) string {
	return fmt.Sprintf(`// tRPC client — auto-generated by gotrpc init.
// The AppRouter type is generated from your Go handlers by gotrpc generate.
import { createTRPCClient, httpLink } from "@trpc/client";
import type { %s } from "./generated/router";

export const trpc = createTRPCClient<%s>({
  links: [httpLink({ url: "/trpc" })],
});
`, routerName, routerName)
}

func trpcWSTemplate(routerName string) string {
	return fmt.Sprintf(`// tRPC client with WebSocket support — auto-generated by gotrpc init.
// The AppRouter type is generated from your Go handlers by gotrpc generate.
import {
  createTRPCClient,
  httpLink,
  splitLink,
  wsLink,
} from "@trpc/client";
import type { %s } from "./generated/router";

const url = window.location.origin + "/trpc";
const wsUrl = url.replace(/^http/, "ws");

export const trpc = createTRPCClient<%s>({
  links: [
    splitLink({
      condition: (op) => op.type === "subscription",
      true: wsLink({ url: wsUrl }),
      false: httpLink({ url }),
    }),
  ],
});
`, routerName, routerName)
}

func runInit(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}

	useWS, _ := cmd.Flags().GetBool("ws")
	sourceFlag, _ := cmd.Flags().GetString("source")
	webFlag, _ := cmd.Flags().GetString("web")

	// Detect or use overrides
	source := detectGoSource(cwd)
	if sourceFlag != "" {
		source = sourceFlag
	}
	webDir := detectWebDir(cwd)
	if webFlag != "" {
		webDir = webFlag
	}
	srcDir := detectSrcDir(cwd, webDir)

	cfg := GoTRPCConfig{
		Source: "./" + source,
		Output: "./" + filepath.Join(webDir, srcDir, "generated/router.d.ts"),
		Router: "AppRouter",
	}

	green := "\033[32m"
	bold := "\033[1m"
	dim := "\033[2m"
	reset := "\033[0m"

	// Show detected configuration
	fmt.Println()
	fmt.Printf("  %sDetected:%s\n", dim, reset)
	fmt.Printf("    Go source  %s→%s %s./%s%s\n", dim, reset, bold, source, reset)
	fmt.Printf("    Web dir    %s→%s %s./%s%s\n", dim, reset, bold, webDir, reset)
	if srcDir != "" {
		fmt.Printf("    Src dir    %s→%s %s./%s/%s%s\n", dim, reset, bold, webDir, srcDir, reset)
	}
	fmt.Println()

	// Write gotrpc.json
	configPath := filepath.Join(cwd, configFileName)
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("  %s~%s %s%s%s already exists, skipping\n", dim, reset, dim, configFileName, reset)
	} else {
		data, err := json.MarshalIndent(cfg, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to marshal config: %w", err)
		}
		data = append(data, '\n')
		if err := os.WriteFile(configPath, data, 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", configFileName, err)
		}
		fmt.Printf("  %s✓%s %s\n", green, reset, configFileName)
	}

	// Create source directory and sample handler
	sourceDir := filepath.Join(cwd, source)
	if err := os.MkdirAll(sourceDir, 0o755); err != nil {
		return fmt.Errorf("failed to create source dir: %w", err)
	}

	handlerPath := filepath.Join(sourceDir, "main.go")
	relHandlerPath := filepath.Join(source, "main.go")
	if _, err := os.Stat(handlerPath); err == nil {
		fmt.Printf("  %s~%s %s%s%s already exists, skipping\n", dim, reset, dim, relHandlerPath, reset)
	} else {
		template := sampleHandlerTemplate()
		if err := os.WriteFile(handlerPath, []byte(template), 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", relHandlerPath, err)
		}
		fmt.Printf("  %s✓%s %s\n", green, reset, relHandlerPath)
	}

	// Create generated directory with .gitignore
	generatedDir := filepath.Join(cwd, webDir, srcDir, "generated")
	if err := os.MkdirAll(generatedDir, 0o755); err != nil {
		return fmt.Errorf("failed to create generated dir: %w", err)
	}

	gitignorePath := filepath.Join(generatedDir, ".gitignore")
	if _, err := os.Stat(gitignorePath); err != nil {
		if err := os.WriteFile(gitignorePath, []byte(generatedGitignore), 0o644); err != nil {
			return fmt.Errorf("failed to write .gitignore: %w", err)
		}
		fmt.Printf("  %s✓%s %s\n", green, reset, filepath.Join(webDir, srcDir, "generated/.gitignore"))
	}

	// Create trpc.ts if it doesn't exist
	trpcPath := filepath.Join(cwd, webDir, srcDir, "trpc.ts")
	relTrpcPath := filepath.Join(webDir, srcDir, "trpc.ts")
	if _, err := os.Stat(trpcPath); err == nil {
		fmt.Printf("  %s~%s %s%s%s already exists, skipping\n", dim, reset, dim, relTrpcPath, reset)
	} else {
		var template string
		if useWS {
			template = trpcWSTemplate(cfg.Router)
		} else {
			template = trpcHTTPTemplate(cfg.Router)
		}
		if err := os.WriteFile(trpcPath, []byte(template), 0o644); err != nil {
			return fmt.Errorf("failed to write trpc.ts: %w", err)
		}
		fmt.Printf("  %s✓%s %s\n", green, reset, relTrpcPath)
	}

	// Print project tree
	cyan := "\033[36m"
	genRel := filepath.Join(webDir, srcDir, "generated")
	fmt.Printf("\n  %sProject structure:%s\n", bold, reset)
	fmt.Printf("    %s%s/%s\n", cyan, source, reset)
	fmt.Printf("      main.go          %s← your Go handlers%s\n", dim, reset)
	fmt.Printf("    %s%s/%s\n", cyan, webDir, reset)
	if srcDir != "" {
		fmt.Printf("      %s/\n", srcDir)
		fmt.Printf("        %s/\n", strings.TrimPrefix(genRel, webDir+"/"+srcDir+"/"))
		fmt.Printf("          router.d.ts  %s← auto-generated (don't edit)%s\n", dim, reset)
		fmt.Printf("        trpc.ts        %s← tRPC client setup%s\n", dim, reset)
	} else {
		fmt.Printf("      %s/\n", strings.TrimPrefix(genRel, webDir+"/"))
		fmt.Printf("        router.d.ts    %s← auto-generated (don't edit)%s\n", dim, reset)
		fmt.Printf("      trpc.ts          %s← tRPC client setup%s\n", dim, reset)
	}

	fmt.Printf("\n  %sNext steps:%s\n", bold, reset)
	fmt.Printf("    %s$%s npm install @trpc/client @trpc/server\n", dim, reset)
	fmt.Printf("    %s$%s gotrpc generate\n", dim, reset)
	fmt.Printf("    %s$%s gotrpc generate --watch  %s← re-generates on file changes%s\n", dim, reset, dim, reset)
	fmt.Println()

	return nil
}

// detectGoSource looks for common Go API directory names.
func detectGoSource(dir string) string {
	candidates := []string{"api", "server", "backend", "cmd"}
	for _, c := range candidates {
		if info, err := os.Stat(filepath.Join(dir, c)); err == nil && info.IsDir() {
			// Check for go.mod in the candidate or its parent
			if _, err := os.Stat(filepath.Join(dir, c, "go.mod")); err == nil {
				return c
			}
			if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
				return c
			}
		}
	}
	return "api"
}

// detectWebDir looks for common web/frontend directory names.
func detectWebDir(dir string) string {
	candidates := []string{"web", "frontend", "client", "app"}
	for _, c := range candidates {
		if info, err := os.Stat(filepath.Join(dir, c)); err == nil && info.IsDir() {
			if _, err := os.Stat(filepath.Join(dir, c, "package.json")); err == nil {
				return c
			}
		}
	}
	return "web"
}

// detectSrcDir checks if the web directory uses a src/ subdirectory.
func detectSrcDir(projectDir, webDir string) string {
	srcPath := filepath.Join(projectDir, webDir, "src")
	if info, err := os.Stat(srcPath); err == nil && info.IsDir() {
		return "src"
	}
	return ""
}
