package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// GenerateOptions configures the TypeScript generation.
type GenerateOptions struct {
	OutputPath string
	RouterName string // defaults to "AppRouter"
	SourcePath string
	Format     string // "dts" (default) or "ts"
}

// Generate parses the Go source and generates the .d.ts file.
func Generate(opts GenerateOptions) error {
	if opts.RouterName == "" {
		opts.RouterName = "AppRouter"
	}

	result, err := ParsePackage(opts.SourcePath, opts.RouterName)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: type-checked parsing failed: %v\n", err)
		fmt.Fprintf(os.Stderr, "warning: falling back to AST parser (types may be incomplete)\n")
		result, err = ParseDir(opts.SourcePath)
		if err != nil {
			return fmt.Errorf("failed to parse source: %w", err)
		}
	}

	if len(result.Procedures) == 0 {
		return fmt.Errorf("no tRPC procedures found in %s", opts.SourcePath)
	}

	var output string
	if opts.Format == "ts" {
		output = generateTS(result, opts)
	} else {
		output = generateDTS(result, opts)
	}

	// Ensure output directory exists
	dir := filepath.Dir(opts.OutputPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(opts.OutputPath, []byte(output), 0o644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}

// GenerateFromProcedures generates a .d.ts string from pre-parsed procedure info.
func GenerateFromProcedures(procedures []ProcedureInfo, routerName string) string {
	result := &ParseResult{
		Procedures: procedures,
		RouterVar:  routerName,
	}
	return generateDTS(result, GenerateOptions{RouterName: routerName})
}

func generateDTS(result *ParseResult, opts GenerateOptions) string {
	mapper := NewTypeMapper()
	mapper.RegisterEnums(result.Enums)
	var b strings.Builder

	b.WriteString("// Code generated by go-trpc. DO NOT EDIT.\n")
	if opts.SourcePath != "" {
		b.WriteString(fmt.Sprintf("// Source: %s\n", opts.SourcePath))
	}
	b.WriteString("\n")

	// Collect type mappings for all procedures
	type procTS struct {
		name     string
		procType string
		inputTS  string
		outputTS string
	}

	// Build struct defs map for AST fallback type resolution
	structDefsMap := make(map[string]*StructDef)
	for i := range result.StructDefs {
		structDefsMap[result.StructDefs[i].Name] = &result.StructDefs[i]
	}

	// Track AST-resolved named types for export
	astNamedTypes := make(map[string]string) // name -> TS definition

	var procs []procTS
	for _, p := range result.Procedures {
		inputTS := "void"
		outputTS := "void"

		if p.InputType != nil {
			inputTS = mapper.MapType(p.InputType)
			if inputTS == "Record<string, never>" {
				inputTS = "void"
			}
		} else if p.InputTypeName != "" {
			inputTS = mapASTType(p.InputTypeName, structDefsMap, astNamedTypes)
		}

		if p.OutputType != nil {
			outputTS = mapper.MapType(p.OutputType)
		} else if p.OutputTypeName != "" {
			outputTS = mapASTType(p.OutputTypeName, structDefsMap, astNamedTypes)
		}

		procs = append(procs, procTS{
			name:     p.Name,
			procType: p.Type,
			inputTS:  inputTS,
			outputTS: outputTS,
		})
	}

	// Write named type definitions (from type checker)
	namedTypes := mapper.NamedTypes()
	if len(namedTypes) > 0 {
		// Sort for deterministic output
		names := make([]string, 0, len(namedTypes))
		for name := range namedTypes {
			names = append(names, name)
		}
		sort.Strings(names)

		for _, name := range names {
			t := namedTypes[name]
			b.WriteString(fmt.Sprintf("type %s = %s\n\n", name, t.Definition))
		}
	}

	// Write AST-resolved named types (from fallback parser)
	if len(astNamedTypes) > 0 {
		astNames := make([]string, 0, len(astNamedTypes))
		for name := range astNamedTypes {
			astNames = append(astNames, name)
		}
		sort.Strings(astNames)

		for _, name := range astNames {
			b.WriteString(fmt.Sprintf("type %s = %s\n\n", name, astNamedTypes[name]))
		}
	}

	// Write AppRouter type
	routerName := opts.RouterName
	if routerName == "" {
		routerName = "AppRouter"
	}

	// Build nested router tree from dotted procedure names
	type routerNode struct {
		children map[string]*routerNode
		proc     *procTS // leaf node = procedure
	}
	root := &routerNode{children: make(map[string]*routerNode)}

	for i := range procs {
		p := &procs[i]
		parts := strings.Split(p.name, ".")
		node := root
		for _, part := range parts[:len(parts)-1] {
			if node.children[part] == nil {
				node.children[part] = &routerNode{children: make(map[string]*routerNode)}
			}
			node = node.children[part]
		}
		leafName := parts[len(parts)-1]
		if node.children[leafName] == nil {
			node.children[leafName] = &routerNode{children: make(map[string]*routerNode)}
		}
		node.children[leafName].proc = p
	}

	var writeNode func(node *routerNode, indent int)
	writeNode = func(node *routerNode, indent int) {
		pad := strings.Repeat("  ", indent)
		// Sort keys for deterministic output
		keys := make([]string, 0, len(node.children))
		for k := range node.children {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, key := range keys {
			child := node.children[key]
			if child.proc != nil {
				// Leaf: write procedure definition (compatible with @trpc/client v11)
				// Must satisfy Procedure<TType, TDef> interface: _def, meta, and callable
				b.WriteString(fmt.Sprintf("%s%s: {\n", pad, key))
				b.WriteString(fmt.Sprintf("%s  _def: {\n", pad))
				b.WriteString(fmt.Sprintf("%s    $types: { input: %s; output: %s };\n", pad, child.proc.inputTS, child.proc.outputTS))
				b.WriteString(fmt.Sprintf("%s    procedure: true;\n", pad))
				b.WriteString(fmt.Sprintf("%s    type: \"%s\";\n", pad, child.proc.procType))
				b.WriteString(fmt.Sprintf("%s    meta: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s    experimental_caller: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s    inputs: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s  };\n", pad))
				b.WriteString(fmt.Sprintf("%s  meta: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s  (...args: any[]): any;\n", pad))
				b.WriteString(fmt.Sprintf("%s};\n", pad))
			} else {
				// Namespace: write nested object
				b.WriteString(fmt.Sprintf("%s%s: {\n", pad, key))
				writeNode(child, indent+1)
				b.WriteString(fmt.Sprintf("%s};\n", pad))
			}
		}
	}

	// Write the procedure record type
	b.WriteString(fmt.Sprintf("type _%sRecord = {\n", routerName))
	writeNode(root, 1)
	b.WriteString("};\n\n")

	// Write AppRouter as a union of Router shape + record (compatible with @trpc/client)
	// Import the Router type from @trpc/server for full compatibility
	// We use a conditional: if @trpc/server is available, use its types; otherwise define standalone
	b.WriteString("// @trpc/client compatibility — wraps the record as a Router\n")
	b.WriteString("// eslint-disable-next-line @typescript-eslint/no-empty-interface\n")
	b.WriteString(fmt.Sprintf("interface %s extends _TRPCRouter<_%sRecord> {}\n\n", routerName, routerName))

	// Write the helper type that creates a Router-compatible wrapper
	// This avoids importing from @trpc/server by inlining the minimal shape
	b.WriteString("type _TRPCRouter<TRecord> = {\n")
	b.WriteString("  _def: {\n")
	b.WriteString("    _config: {\n")
	b.WriteString("      $types: { transformer: false; errorShape: any; ctx: any; meta: any };\n")
	b.WriteString("      transformer: any;\n")
	b.WriteString("      errorFormatter: any;\n")
	b.WriteString("      allowOutsideOfServer: boolean;\n")
	b.WriteString("      isServer: boolean;\n")
	b.WriteString("      isDev: boolean;\n")
	b.WriteString("    };\n")
	b.WriteString("    router: true;\n")
	b.WriteString("    procedures: TRecord;\n")
	b.WriteString("    record: TRecord;\n")
	b.WriteString("    lazy: Record<string, never>;\n")
	b.WriteString("  };\n")
	b.WriteString("  createCaller: any;\n")
	b.WriteString("} & TRecord;\n\n")

	// Export types
	var exportNames []string
	exportNames = append(exportNames, routerName)
	for name := range namedTypes {
		exportNames = append(exportNames, name)
	}
	for name := range astNamedTypes {
		exportNames = append(exportNames, name)
	}
	sort.Strings(exportNames)
	b.WriteString(fmt.Sprintf("export type { %s };\n\n", strings.Join(exportNames, ", ")))

	// Helper types: RouterInputs and RouterOutputs (using dotted keys)
	b.WriteString("export type RouterInputs = {\n")
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  \"%s\": %s;\n", p.name, p.inputTS))
	}
	b.WriteString("};\n\n")

	b.WriteString("export type RouterOutputs = {\n")
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  \"%s\": %s;\n", p.name, p.outputTS))
	}
	b.WriteString("};\n")

	return b.String()
}

func generateTS(result *ParseResult, opts GenerateOptions) string {
	routerName := opts.RouterName
	if routerName == "" {
		routerName = "AppRouter"
	}

	var b strings.Builder

	b.WriteString("// Code generated by go-trpc. DO NOT EDIT.\n")
	if opts.SourcePath != "" {
		b.WriteString(fmt.Sprintf("// Source: %s\n", opts.SourcePath))
	}
	b.WriteString("\n")

	// Re-export types from .d.ts
	dtsName := strings.TrimSuffix(filepath.Base(opts.OutputPath), ".ts")
	if dtsName == "" {
		dtsName = "router"
	}
	b.WriteString(fmt.Sprintf("export type { %s } from \"./%s\";\n\n", routerName, dtsName))

	// Runtime procedure metadata
	b.WriteString("export const procedures = {\n")
	// Sort for deterministic output
	sorted := make([]ProcedureInfo, len(result.Procedures))
	copy(sorted, result.Procedures)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	for _, p := range sorted {
		b.WriteString(fmt.Sprintf("  \"%s\": { type: \"%s\" as const },\n", p.Name, p.Type))
	}
	b.WriteString("} as const;\n\n")

	b.WriteString("export type ProcedureName = keyof typeof procedures;\n")

	return b.String()
}

// mapASTType converts a Go type expression string (from AST parsing) to TypeScript.
// It resolves named types against structDefsMap and registers them in astNamedTypes.
func mapASTType(goType string, structDefsMap map[string]*StructDef, astNamedTypes map[string]string) string {
	return mapASTTypeInner(goType, structDefsMap, astNamedTypes, make(map[string]bool))
}

func mapASTTypeInner(goType string, structDefsMap map[string]*StructDef, astNamedTypes map[string]string, seen map[string]bool) string {
	goType = strings.TrimSpace(goType)

	// Empty or void
	if goType == "" || goType == "struct{}" {
		return "void"
	}

	// Pointer: *T → T | null
	if strings.HasPrefix(goType, "*") {
		inner := mapASTTypeInner(goType[1:], structDefsMap, astNamedTypes, seen)
		return inner + " | null"
	}

	// Slice: []T → T[]
	if strings.HasPrefix(goType, "[]") {
		inner := mapASTTypeInner(goType[2:], structDefsMap, astNamedTypes, seen)
		if strings.Contains(inner, "|") {
			return "(" + inner + ")[]"
		}
		return inner + "[]"
	}

	// Map: map[K]V → Record<K, V>
	if strings.HasPrefix(goType, "map[") {
		rest := goType[4:]
		bracketDepth := 1
		keyEnd := 0
		for i, ch := range rest {
			if ch == '[' {
				bracketDepth++
			} else if ch == ']' {
				bracketDepth--
				if bracketDepth == 0 {
					keyEnd = i
					break
				}
			}
		}
		keyType := mapASTTypeInner(rest[:keyEnd], structDefsMap, astNamedTypes, seen)
		valType := mapASTTypeInner(rest[keyEnd+1:], structDefsMap, astNamedTypes, seen)
		return "Record<" + keyType + ", " + valType + ">"
	}

	// Inline struct: struct{Name:Type:Tag;...}
	if strings.HasPrefix(goType, "struct{") && strings.HasSuffix(goType, "}") {
		inner := goType[7 : len(goType)-1]
		if inner == "" {
			return "void"
		}
		return mapInlineStructAST(inner, structDefsMap, astNamedTypes, seen)
	}

	// Qualified types (e.g., time.Time, uuid.UUID)
	if strings.Contains(goType, ".") {
		parts := strings.SplitN(goType, ".", 2)
		switch goType {
		case "time.Time", "uuid.UUID":
			return "string"
		case "json.RawMessage":
			return "unknown"
		default:
			// Try the short name
			return mapASTTypeInner(parts[1], structDefsMap, astNamedTypes, seen)
		}
	}

	// interface{}
	if goType == "interface{}" {
		return "unknown"
	}

	// Go primitives
	switch goType {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "number"
	case "byte":
		return "number"
	case "error":
		return "string"
	}

	// Named type — look up in struct defs
	if def, ok := structDefsMap[goType]; ok {
		if seen[goType] {
			return goType // prevent infinite recursion
		}
		seen[goType] = true

		// Build the TS definition and register it
		tsDef := mapStructDefToTS(def, structDefsMap, astNamedTypes, seen)
		astNamedTypes[goType] = tsDef
		delete(seen, goType)
		return goType
	}

	// Unknown type — use the name as-is (might be from another package)
	if len(goType) > 0 && unicode.IsUpper(rune(goType[0])) {
		return goType
	}

	return "unknown"
}

// mapInlineStructAST converts an inline struct definition string to TypeScript.
func mapInlineStructAST(fields string, structDefsMap map[string]*StructDef, astNamedTypes map[string]string, seen map[string]bool) string {
	parts := strings.Split(fields, ";")
	var tsFields []string
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		// Format: Name:Type:Tag
		segments := strings.SplitN(part, ":", 3)
		if len(segments) < 2 {
			continue
		}
		fieldName := segments[0]
		fieldType := segments[1]
		tag := ""
		if len(segments) >= 3 {
			tag = segments[2]
		}

		jsonName := lowerFirst(fieldName)
		optional := false
		if tag != "" {
			tagName, tagOptional := parseJSONTagRaw(tag)
			if tagName == "-" {
				continue
			}
			if tagName != "" {
				jsonName = tagName
			}
			optional = tagOptional
		}

		tsType := mapASTTypeInner(fieldType, structDefsMap, astNamedTypes, seen)
		optMark := ""
		if optional {
			optMark = "?"
		}
		tsFields = append(tsFields, fmt.Sprintf("%s%s: %s", jsonName, optMark, tsType))
	}

	if len(tsFields) == 0 {
		return "void"
	}
	return "{ " + strings.Join(tsFields, "; ") + " }"
}

// mapStructDefToTS converts a StructDef to a TypeScript object type string.
func mapStructDefToTS(def *StructDef, structDefsMap map[string]*StructDef, astNamedTypes map[string]string, seen map[string]bool) string {
	if len(def.Fields) == 0 {
		return "Record<string, never>"
	}

	var tsFields []string
	for _, f := range def.Fields {
		if f.JSONName == "-" {
			continue
		}
		tsType := mapASTTypeInner(f.TypeExpr, structDefsMap, astNamedTypes, seen)
		optMark := ""
		if f.Optional {
			optMark = "?"
		}
		tsFields = append(tsFields, fmt.Sprintf("  %s%s: %s;", f.JSONName, optMark, tsType))
	}

	if len(tsFields) == 0 {
		return "Record<string, never>"
	}
	return "{\n" + strings.Join(tsFields, "\n") + "\n}"
}

// parseJSONTagRaw extracts name and omitempty from a raw struct tag value (with backticks).
func parseJSONTagRaw(tag string) (string, bool) {
	tag = strings.Trim(tag, "`")
	const prefix = `json:"`
	idx := strings.Index(tag, prefix)
	if idx < 0 {
		return "", false
	}
	rest := tag[idx+len(prefix):]
	end := strings.Index(rest, `"`)
	if end < 0 {
		return "", false
	}
	jsonVal := rest[:end]
	if jsonVal == "-" {
		return "-", false
	}
	parts := strings.Split(jsonVal, ",")
	name := parts[0]
	optional := false
	for _, p := range parts[1:] {
		if p == "omitempty" {
			optional = true
		}
	}
	return name, optional
}
