package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateOptions configures the TypeScript generation.
type GenerateOptions struct {
	OutputPath string
	RouterName string // defaults to "AppRouter"
	SourcePath string
}

// Generate parses the Go source and generates the .d.ts file.
func Generate(opts GenerateOptions) error {
	if opts.RouterName == "" {
		opts.RouterName = "AppRouter"
	}

	result, err := ParsePackage(opts.SourcePath, opts.RouterName)
	if err != nil {
		// Fallback to simple AST parsing
		result, err = ParseDir(opts.SourcePath)
		if err != nil {
			return fmt.Errorf("failed to parse source: %w", err)
		}
	}

	if len(result.Procedures) == 0 {
		return fmt.Errorf("no tRPC procedures found in %s", opts.SourcePath)
	}

	output := generateDTS(result, opts)

	// Ensure output directory exists
	dir := filepath.Dir(opts.OutputPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(opts.OutputPath, []byte(output), 0o644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}

// GenerateFromProcedures generates a .d.ts string from pre-parsed procedure info.
func GenerateFromProcedures(procedures []ProcedureInfo, routerName string) string {
	result := &ParseResult{
		Procedures: procedures,
		RouterVar:  routerName,
	}
	return generateDTS(result, GenerateOptions{RouterName: routerName})
}

func generateDTS(result *ParseResult, opts GenerateOptions) string {
	mapper := NewTypeMapper()
	var b strings.Builder

	b.WriteString("// Code generated by go-trpc. DO NOT EDIT.\n")
	if opts.SourcePath != "" {
		b.WriteString(fmt.Sprintf("// Source: %s\n", opts.SourcePath))
	}
	b.WriteString("\n")

	// Collect type mappings for all procedures
	type procTS struct {
		name     string
		procType string
		inputTS  string
		outputTS string
	}

	var procs []procTS
	for _, p := range result.Procedures {
		inputTS := "void"
		outputTS := "void"

		if p.InputType != nil {
			inputTS = mapper.MapType(p.InputType)
		}
		if p.OutputType != nil {
			outputTS = mapper.MapType(p.OutputType)
		}

		procs = append(procs, procTS{
			name:     p.Name,
			procType: p.Type,
			inputTS:  inputTS,
			outputTS: outputTS,
		})
	}

	// Write named type definitions
	namedTypes := mapper.NamedTypes()
	if len(namedTypes) > 0 {
		// Sort for deterministic output
		names := make([]string, 0, len(namedTypes))
		for name := range namedTypes {
			names = append(names, name)
		}
		sort.Strings(names)

		for _, name := range names {
			t := namedTypes[name]
			b.WriteString(fmt.Sprintf("type %s = %s\n\n", name, t.Definition))
		}
	}

	// Write AppRouter type
	routerName := opts.RouterName
	if routerName == "" {
		routerName = "AppRouter"
	}

	b.WriteString(fmt.Sprintf("type %s = {\n", routerName))
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  %s: {\n", p.name))
		b.WriteString("    _def: {\n")
		b.WriteString(fmt.Sprintf("      _input_in: %s;\n", p.inputTS))
		b.WriteString(fmt.Sprintf("      _input_out: %s;\n", p.inputTS))
		b.WriteString(fmt.Sprintf("      _output_in: %s;\n", p.outputTS))
		b.WriteString(fmt.Sprintf("      _output_out: %s;\n", p.outputTS))
		b.WriteString(fmt.Sprintf("      _type: \"%s\";\n", p.procType))
		b.WriteString("    };\n")
		b.WriteString("  };\n")
	}
	b.WriteString("};\n\n")

	// Export types
	var exportNames []string
	exportNames = append(exportNames, routerName)
	for name := range namedTypes {
		exportNames = append(exportNames, name)
	}
	sort.Strings(exportNames)
	b.WriteString(fmt.Sprintf("export type { %s };\n\n", strings.Join(exportNames, ", ")))

	// Helper types: RouterInputs and RouterOutputs
	b.WriteString("export type RouterInputs = {\n")
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  %s: %s;\n", p.name, p.inputTS))
	}
	b.WriteString("};\n\n")

	b.WriteString("export type RouterOutputs = {\n")
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  %s: %s;\n", p.name, p.outputTS))
	}
	b.WriteString("};\n")

	return b.String()
}
