package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateOptions configures the TypeScript generation.
type GenerateOptions struct {
	OutputPath string
	RouterName string // defaults to "AppRouter"
	SourcePath string
}

// Generate parses the Go source and generates the .d.ts file.
func Generate(opts GenerateOptions) error {
	if opts.RouterName == "" {
		opts.RouterName = "AppRouter"
	}

	result, err := ParsePackage(opts.SourcePath, opts.RouterName)
	if err != nil {
		// Fallback to simple AST parsing
		result, err = ParseDir(opts.SourcePath)
		if err != nil {
			return fmt.Errorf("failed to parse source: %w", err)
		}
	}

	if len(result.Procedures) == 0 {
		return fmt.Errorf("no tRPC procedures found in %s", opts.SourcePath)
	}

	output := generateDTS(result, opts)

	// Ensure output directory exists
	dir := filepath.Dir(opts.OutputPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(opts.OutputPath, []byte(output), 0o644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}

// GenerateFromProcedures generates a .d.ts string from pre-parsed procedure info.
func GenerateFromProcedures(procedures []ProcedureInfo, routerName string) string {
	result := &ParseResult{
		Procedures: procedures,
		RouterVar:  routerName,
	}
	return generateDTS(result, GenerateOptions{RouterName: routerName})
}

func generateDTS(result *ParseResult, opts GenerateOptions) string {
	mapper := NewTypeMapper()
	mapper.RegisterEnums(result.Enums)
	var b strings.Builder

	b.WriteString("// Code generated by go-trpc. DO NOT EDIT.\n")
	if opts.SourcePath != "" {
		b.WriteString(fmt.Sprintf("// Source: %s\n", opts.SourcePath))
	}
	b.WriteString("\n")

	// Collect type mappings for all procedures
	type procTS struct {
		name     string
		procType string
		inputTS  string
		outputTS string
	}

	var procs []procTS
	for _, p := range result.Procedures {
		inputTS := "void"
		outputTS := "void"

		if p.InputType != nil {
			inputTS = mapper.MapType(p.InputType)
		}
		if p.OutputType != nil {
			outputTS = mapper.MapType(p.OutputType)
		}

		procs = append(procs, procTS{
			name:     p.Name,
			procType: p.Type,
			inputTS:  inputTS,
			outputTS: outputTS,
		})
	}

	// Write named type definitions
	namedTypes := mapper.NamedTypes()
	if len(namedTypes) > 0 {
		// Sort for deterministic output
		names := make([]string, 0, len(namedTypes))
		for name := range namedTypes {
			names = append(names, name)
		}
		sort.Strings(names)

		for _, name := range names {
			t := namedTypes[name]
			b.WriteString(fmt.Sprintf("type %s = %s\n\n", name, t.Definition))
		}
	}

	// Write AppRouter type
	routerName := opts.RouterName
	if routerName == "" {
		routerName = "AppRouter"
	}

	// Build nested router tree from dotted procedure names
	type routerNode struct {
		children map[string]*routerNode
		proc     *procTS // leaf node = procedure
	}
	root := &routerNode{children: make(map[string]*routerNode)}

	for i := range procs {
		p := &procs[i]
		parts := strings.Split(p.name, ".")
		node := root
		for _, part := range parts[:len(parts)-1] {
			if node.children[part] == nil {
				node.children[part] = &routerNode{children: make(map[string]*routerNode)}
			}
			node = node.children[part]
		}
		leafName := parts[len(parts)-1]
		if node.children[leafName] == nil {
			node.children[leafName] = &routerNode{children: make(map[string]*routerNode)}
		}
		node.children[leafName].proc = p
	}

	var writeNode func(node *routerNode, indent int)
	writeNode = func(node *routerNode, indent int) {
		pad := strings.Repeat("  ", indent)
		// Sort keys for deterministic output
		keys := make([]string, 0, len(node.children))
		for k := range node.children {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, key := range keys {
			child := node.children[key]
			if child.proc != nil {
				// Leaf: write procedure definition (compatible with @trpc/client v11)
				// Must satisfy Procedure<TType, TDef> interface: _def, meta, and callable
				b.WriteString(fmt.Sprintf("%s%s: {\n", pad, key))
				b.WriteString(fmt.Sprintf("%s  _def: {\n", pad))
				b.WriteString(fmt.Sprintf("%s    $types: { input: %s; output: %s };\n", pad, child.proc.inputTS, child.proc.outputTS))
				b.WriteString(fmt.Sprintf("%s    procedure: true;\n", pad))
				b.WriteString(fmt.Sprintf("%s    type: \"%s\";\n", pad, child.proc.procType))
				b.WriteString(fmt.Sprintf("%s    meta: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s    experimental_caller: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s    inputs: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s  };\n", pad))
				b.WriteString(fmt.Sprintf("%s  meta: any;\n", pad))
				b.WriteString(fmt.Sprintf("%s  (...args: any[]): any;\n", pad))
				b.WriteString(fmt.Sprintf("%s};\n", pad))
			} else {
				// Namespace: write nested object
				b.WriteString(fmt.Sprintf("%s%s: {\n", pad, key))
				writeNode(child, indent+1)
				b.WriteString(fmt.Sprintf("%s};\n", pad))
			}
		}
	}

	// Write the procedure record type
	b.WriteString(fmt.Sprintf("type _%sRecord = {\n", routerName))
	writeNode(root, 1)
	b.WriteString("};\n\n")

	// Write AppRouter as a union of Router shape + record (compatible with @trpc/client)
	// Import the Router type from @trpc/server for full compatibility
	// We use a conditional: if @trpc/server is available, use its types; otherwise define standalone
	b.WriteString("// @trpc/client compatibility — wraps the record as a Router\n")
	b.WriteString("// eslint-disable-next-line @typescript-eslint/no-empty-interface\n")
	b.WriteString(fmt.Sprintf("interface %s extends _TRPCRouter<_%sRecord> {}\n\n", routerName, routerName))

	// Write the helper type that creates a Router-compatible wrapper
	// This avoids importing from @trpc/server by inlining the minimal shape
	b.WriteString("type _TRPCRouter<TRecord> = {\n")
	b.WriteString("  _def: {\n")
	b.WriteString("    _config: {\n")
	b.WriteString("      $types: { transformer: false; errorShape: any; ctx: any; meta: any };\n")
	b.WriteString("      transformer: any;\n")
	b.WriteString("      errorFormatter: any;\n")
	b.WriteString("      allowOutsideOfServer: boolean;\n")
	b.WriteString("      isServer: boolean;\n")
	b.WriteString("      isDev: boolean;\n")
	b.WriteString("    };\n")
	b.WriteString("    router: true;\n")
	b.WriteString("    procedures: TRecord;\n")
	b.WriteString("    record: TRecord;\n")
	b.WriteString("    lazy: Record<string, never>;\n")
	b.WriteString("  };\n")
	b.WriteString("  createCaller: any;\n")
	b.WriteString("} & TRecord;\n\n")

	// Export types
	var exportNames []string
	exportNames = append(exportNames, routerName)
	for name := range namedTypes {
		exportNames = append(exportNames, name)
	}
	sort.Strings(exportNames)
	b.WriteString(fmt.Sprintf("export type { %s };\n\n", strings.Join(exportNames, ", ")))

	// Helper types: RouterInputs and RouterOutputs (using dotted keys)
	b.WriteString("export type RouterInputs = {\n")
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  \"%s\": %s;\n", p.name, p.inputTS))
	}
	b.WriteString("};\n\n")

	b.WriteString("export type RouterOutputs = {\n")
	for _, p := range procs {
		b.WriteString(fmt.Sprintf("  \"%s\": %s;\n", p.name, p.outputTS))
	}
	b.WriteString("};\n")

	return b.String()
}
