package codegen

import (
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"sort"
	"strings"
)

// ConvertGoToTS parses Go type declarations from source code and returns
// their TypeScript equivalents using the same TypeMapper used by the codegen CLI.
//
// The input should contain Go type declarations (no package clause needed):
//
//	type User struct {
//	    Name  string `json:"name"`
//	    Email string `json:"email"`
//	}
func ConvertGoToTS(goCode string) (string, error) {
	// Wrap in a package so go/parser can handle it
	src := "package playground\n\n" + goCode

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "input.go", src, 0)
	if err != nil {
		return "", fmt.Errorf("parse error: %w", err)
	}

	// Type-check to get resolved types
	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue),
		Defs:  make(map[*ast.Ident]types.Object),
	}
	conf := types.Config{
		// Use the default (compiled) importer — reads pre-compiled .a files
		// which is much faster than the source importer (critical for Lambda).
		Importer: importer.Default(),
		Error:    func(err error) {},
	}

	pkg, err := conf.Check("playground", fset, []*ast.File{file}, info)
	if err != nil {
		// Type-check errors are common for playground snippets (missing imports, etc.)
		// Try to continue with whatever types were resolved
		if pkg == nil {
			return "", fmt.Errorf("type check failed: %w", err)
		}
	}

	// Extract enum patterns from const declarations
	enums := extractPlaygroundEnums(file, pkg)

	mapper := NewTypeMapper()
	mapper.RegisterEnums(enums)

	// Collect named types in declaration order
	var typeNames []string
	for _, name := range pkg.Scope().Names() {
		obj := pkg.Scope().Lookup(name)
		if _, ok := obj.(*types.TypeName); ok {
			typeNames = append(typeNames, name)
		}
	}
	sort.Strings(typeNames)

	if len(typeNames) == 0 {
		return "// No types found in input", nil
	}

	// Map each type
	var b strings.Builder
	b.WriteString("// Generated by go-trpc codegen\n\n")

	for _, name := range typeNames {
		obj := pkg.Scope().Lookup(name)
		tn := obj.(*types.TypeName)
		mapper.MapType(tn.Type())
	}

	// Write named type definitions
	namedTypes := mapper.NamedTypes()
	names := make([]string, 0, len(namedTypes))
	for n := range namedTypes {
		names = append(names, n)
	}
	sort.Strings(names)

	for i, name := range names {
		t := namedTypes[name]
		b.WriteString(fmt.Sprintf("type %s = %s", name, t.Definition))
		if i < len(names)-1 {
			b.WriteString("\n\n")
		}
	}

	return b.String(), nil
}

// extractPlaygroundEnums detects enum patterns in playground code.
func extractPlaygroundEnums(file *ast.File, pkg *types.Package) []EnumInfo {
	var enums []EnumInfo

	scope := pkg.Scope()
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		tn, ok := obj.(*types.TypeName)
		if !ok {
			continue
		}

		named, ok := tn.Type().(*types.Named)
		if !ok {
			continue
		}

		basic, ok := named.Underlying().(*types.Basic)
		if !ok {
			continue
		}

		isString := basic.Kind() == types.String
		isInt := basic.Kind() == types.Int || basic.Kind() == types.Int8 ||
			basic.Kind() == types.Int16 || basic.Kind() == types.Int32 ||
			basic.Kind() == types.Int64 || basic.Kind() == types.Uint ||
			basic.Kind() == types.Uint8 || basic.Kind() == types.Uint16 ||
			basic.Kind() == types.Uint32 || basic.Kind() == types.Uint64

		if !isString && !isInt {
			continue
		}

		// Find const values of this type
		var values []string
		for _, constName := range scope.Names() {
			constObj := scope.Lookup(constName)
			c, ok := constObj.(*types.Const)
			if !ok {
				continue
			}
			if !types.Identical(c.Type(), named) {
				continue
			}
			val := c.Val().ExactString()
			if isString {
				val = strings.Trim(val, `"`)
			}
			values = append(values, val)
		}

		if len(values) > 0 {
			qualName := name
			if tn.Pkg() != nil {
				qualName = tn.Pkg().Path() + "." + name
			}
			enums = append(enums, EnumInfo{
				TypeName:      name,
				QualifiedName: qualName,
				Values:        values,
				IsString:      isString,
			})
		}
	}

	return enums
}
