import { useState } from "react";
import CodeBlock from "./CodeBlock";

const tabs = [
  {
    id: "go",
    label: "Go Handler",
    language: "go",
    code: `// api/app/handlers.go — Chat backend with go-trpc

// SSE Subscription — real-time message stream
func SubscribeRoom(store *ChatStore) func(ctx context.Context,
    input SubscribeRoomInput) (<-chan Message, error) {
    return func(ctx context.Context,
        input SubscribeRoomInput) (<-chan Message, error) {
        ch := store.Subscribe(input.RoomID)
        // Cleanup when client disconnects
        go func() {
            <-ctx.Done()
            store.Unsubscribe(input.RoomID, ch)
        }()
        return ch, nil
    }
}

// Mutation — send a message and broadcast to subscribers
func SendMessage(store *ChatStore) func(ctx context.Context,
    input SendMessageInput) (Message, error) {
    return func(ctx context.Context,
        input SendMessageInput) (Message, error) {
        msg := Message{
            ID:       generateMsgID(),
            RoomID:   input.RoomID,
            Username: input.Username,
            Content:  input.Content,
        }
        store.AddMessage(msg)
        store.Broadcast(input.RoomID, msg) // Push to SSE clients
        return msg, nil
    }
}

// Register procedures on routers
gotrpc.Subscription(chatRouter, "subscribe", SubscribeRoom(store))
gotrpc.Mutation(chatRouter, "send", SendMessage(store))
gotrpc.Query(roomRouter, "list", ListRooms(store))
gotrpc.Query(roomRouter, "messages", ListMessages(store))

// Nest and protect with middlewares
r := gotrpc.NewRouter()
r.Use(gotrpc.RateLimit(50))
r.Use(gotrpc.MaxConnectionsPerIP(10))
r.Use(gotrpc.MaxInputSize(4096))
r.Merge("room", roomRouter)
r.Merge("chat", chatRouter)`,
  },
  {
    id: "types",
    label: "Generated Types",
    language: "typescript",
    code: `// generated/router.d.ts — Auto-generated by: gotrpc generate ./api

type Room = {
  id: string;
  name: string;
  createdAt: string;
};

type Message = {
  id: string;
  roomId: string;
  username: string;
  content: string;
  createdAt: string;
};

type AppRouter = {
  room: {
    list:     { _def: { _input_in: void;              _output_out: ListRoomsOutput;    _type: "query"; }; };
    create:   { _def: { _input_in: CreateRoomInput;    _output_out: Room;              _type: "mutation"; }; };
    messages: { _def: { _input_in: ListMessagesInput;  _output_out: ListMessagesOutput; _type: "query"; }; };
  };
  chat: {
    send:      { _def: { _input_in: SendMessageInput; _output_out: Message;           _type: "mutation"; }; };
    subscribe: { _def: { _input_in: SubscribeRoomInput; _output_out: Message;          _type: "subscription"; }; };
  };
  health: {
    check: { _def: { _input_in: void;                 _output_out: HealthOutput;      _type: "query"; }; };
  };
};

export type { AppRouter, Room, Message /* ... */ };`,
  },
  {
    id: "typemap",
    label: "Type Map",
    language: "typescript",
    code: `// Go → TypeScript type mapping reference
// Every Go type is automatically converted by the codegen.

// ─── Primitives ──────────────────────────────────────────
// string       → string
// bool         → boolean
// int, int8…64 → number
// uint…64      → number
// float32, 64  → number

// ─── Pointers ────────────────────────────────────────────
// *string      → string | null
// *User        → User | null

// ─── Collections ─────────────────────────────────────────
// []string        → string[]
// []*User         → (User | null)[]     // parens added automatically
// [4]int          → number[]
// []byte          → string              // base64 convention
// map[string]int  → Record<string, number>

// ─── Named Types ─────────────────────────────────────────
// type UserID string   →  type UserID = string
// type Count int       →  type Count = number

// ─── Structs & JSON Tags ─────────────────────────────────
// Go:
//   type User struct {
//       Name     string  \`json:"name"\`
//       Bio      string  \`json:"bio,omitempty"\`
//       Password string  \`json:"-"\`
//       Count    int     \`json:"count,string"\`
//   }
//
// TypeScript:
type User = {
  name: string;
  bio?: string;      // omitempty → optional
  // password: skipped  (json:"-")
  count: string;     // json:",string" → wire type is string
}

// ─── Well-Known Types ────────────────────────────────────
// time.Time             → string     (RFC 3339)
// uuid.UUID             → string
// json.RawMessage       → unknown
// decimal.Decimal       → string
// sql.NullString        → string | null
// sql.NullInt64         → number | null
// sql.NullBool          → boolean | null
// sql.NullTime          → string | null
// decimal.NullDecimal   → string | null

// ─── Enums ───────────────────────────────────────────────
// Go:
//   type Status string
//   const (
//       StatusActive   Status = "active"
//       StatusInactive Status = "inactive"
//   )
//
// TypeScript:
type Status = "active" | "inactive"

// Go (int enum):
//   type Priority int
//   const ( Low Priority = 0; High Priority = 1 )
//
// TypeScript:
type Priority = 0 | 1

// ─── Embedded Structs ────────────────────────────────────
// Go:
//   type Base struct { ID int \`json:"id"\` }
//   type Item struct {
//       Base
//       Name string \`json:"name"\`
//   }
//
// TypeScript (intersection type):
type Item = Base & {
  name: string;
}

// ─── Generics ────────────────────────────────────────────
// Go:
//   type Response[T any] struct {
//       Data  T   \`json:"data"\`
//       Count int \`json:"count"\`
//   }
//
// Response[User] → generates:
type ResponseUser = {
  data: User;
  count: number;
}

// Response[string] → ResponseString
// Response[[]User] → ResponseUser  (sanitized)

// ─── Name Collisions ────────────────────────────────────
// models.User → User
// auth.User   → AuthUser  (auto-disambiguated)`,
  },
  {
    id: "frontend",
    label: "React Usage",
    language: "typescript",
    code: `// web/src/trpc.ts — Client setup with @trpc/client
import { createTRPCClient, httpLink } from "@trpc/client";
import type { AppRouter } from "./generated/router";

export const trpc = createTRPCClient<AppRouter>({
  links: [httpLink({ url: "/trpc" })],
});

// Typed queries
const rooms = await trpc.room.list.query();
//    ^? { rooms: Room[] }

const history = await trpc.room.messages.query({ roomId: "room-1" });
//    ^? { messages: Message[] }

// Typed mutation
const msg = await trpc.chat.send.mutate({
  roomId: "room-1",
  username: "alice",
  content: "Hello!",
});
//    ^? Message — full autocompletion

// SSE Subscription — real-time messages via EventSource
const apiUrl = "/trpc";
const url = \`\${apiUrl}/chat.subscribe?input=\${encodeURIComponent(
  JSON.stringify({ json: { roomId: "room-1" } })
)}\`;

const es = new EventSource(url);
es.addEventListener("data", (e) => {
  const msg = JSON.parse(e.data).result?.data;
  // msg is a new Message pushed from the server
});
// es.close() on unmount

// The tRPC protocol over HTTP:
// GET  /trpc/room.list
// GET  /trpc/room.messages?input={"json":{"roomId":"room-1"}}
// POST /trpc/chat.send  body: {"json":{"roomId":"room-1",...}}
// GET  /trpc/chat.subscribe?input=...  → SSE stream`,
  },
  {
    id: "deploy",
    label: "Koyeb Deploy",
    language: "go",
    code: `// Dockerfile — Multi-stage build for Koyeb

// Stage 1: Build Go server
// FROM golang:1.24 AS api
// WORKDIR /app
// COPY api/ ./api/
// COPY go.work go.work.sum ./
// RUN cd api && go build -o /server ./cmd/local

// Stage 2: Build frontend
// FROM node:22 AS web
// WORKDIR /app
// COPY web/ ./web/
// RUN cd web && npm ci && npm run build

// Stage 3: Slim runtime
// FROM debian:bookworm-slim
// COPY --from=api /server /server
// COPY --from=web /app/web/dist /static
// EXPOSE 8080
// CMD ["/server"]

// api/main.go — Single binary serves both API + static files
package main

import (
    "net/http"
    "os"

    "github.com/sebasusnik/go-trpc-demo/api/app"
    gotrpc "github.com/sebasusnik/go-trpc/pkg/router"
)

func main() {
    r := app.NewRouter()

    r.WithCORS(gotrpc.CORSConfig{
        AllowedOrigins: []string{"*"},
        AllowedHeaders: []string{"Content-Type"},
    })

    mux := http.NewServeMux()
    mux.Handle("/trpc/", r.Handler())

    // Serve built frontend in production
    if _, err := os.Stat("static"); err == nil {
        mux.Handle("/", http.FileServer(http.Dir("static")))
    }

    port := os.Getenv("PORT")
    if port == "" { port = "8080" }
    http.ListenAndServe(":"+port, mux)
}`,
  },
];

export default function CodePanel() {
  const [activeTab, setActiveTab] = useState("go");
  // biome-ignore lint/style/noNonNullAssertion: activeTab always matches a tab id
  const active = tabs.find((t) => t.id === activeTab)!;

  return (
    <div className="flex h-full min-w-0 flex-col">
      <div className="flex shrink-0 overflow-x-auto border-b border-zinc-200">
        {tabs.map((tab) => (
          <button
            type="button"
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`shrink-0 px-3 md:px-4 py-2.5 text-xs font-medium transition-colors cursor-pointer ${
              activeTab === tab.id
                ? "border-b-2 border-go-blue text-go-blue"
                : "text-zinc-500 hover:text-zinc-700"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>
      <div className="flex-1 overflow-auto bg-zinc-950">
        <CodeBlock code={active.code} lang={active.language} />
      </div>
    </div>
  );
}
